services:
  nats:
    image: nats:latest
    command: "-c /etc/nats/nats.conf"
    volumes:
       - ./services/message-brooker/:/etc/nats
    ports:
      - 23422:8080
      - 6222:6222
      - 8222:8222