services:
  nats:
    image: nats:latest
    command: "-c /etc/nats/nats.conf"
    volumes:
       - ./services/message-brooker/:/etc/nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - message-bus
  app-homepage:
    build:
      context: ./apps/homepage
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    networks:
      - message-bus

networks:
  message-bus:
    driver: bridge